MICROSERVICES_DB_CONTAINER_NAME: 'db'
MICROSERVICES_VOTE_URL: 'http://192.168.99.100'
MICROSERVICES_RESULTS_URL: 'http://192.168.99.100:81'
MICROSERVICES_DOCKER_HOST: 'tcp://192.168.99.100:2376'
MICROSERVICES_DOCKER_CERT_PATH: '/home/michalj/.docker/machine/machines/example-votin-app-microservices'

MONOLITH_DB_CONTAINER_NAME: '4dbe8a9c5a42'
MONOLITH_DOCKER_HOST: 'tcp://192.168.99.101:2376'
MONOLITH_DOCKER_CERT_PATH: '/home/michalj/.docker/machine/machines/example-votin-app-monolith'
MONOLITH_VOTE_URL: 'http://192.168.99.101'
MONOLITH_RESULTS_URL: 'http://192.168.99.101/results/'

SPLASH_SERVER_URL: 'http://192.168.99.102:8050'
